# Generated by Django 4.2.11 on 2024-05-21 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgames', models.IntegerField()),
                ('game_name', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026)])),
                ('metacritic_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('developers', models.CharField(blank=True, max_length=100, null=True)),
                ('howlongtobeat', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
