# Generated by Django 4.2.11 on 2024-05-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
