# Generated by Django 4.2.11 on 2024-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0002_rename_username_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
