# Generated by Django 4.2.11 on 2024-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
