# Generated by Django 4.2.11 on 2024-06-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0004_table_name_table_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
