# Generated by Django 4.2.11 on 2024-06-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0006_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id_games',
        ),
    ]
