# Generated by Django 4.2.11 on 2024-08-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0007_remove_games_id_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_genres',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
