# Generated by Django 4.2.11 on 2024-08-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0009_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablesCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
