# Generated by Django 4.2.11 on 2024-08-22 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0010_tablescombined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(1)])),
                ('pfp', models.ImageField(upload_to='profilepics')),
                ('description', models.CharField(max_length=240)),
            ],
        ),
    ]
