# Generated by Django 4.2.11 on 2024-08-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0011_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(upload_to='profilepics/'),
        ),
    ]
