# Generated by Django 4.2.11 on 2024-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0012_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(upload_to='profilepics'),
        ),
    ]
