# Generated by Django 4.2.11 on 2024-08-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0013_alter_profile_nickname_alter_profile_pfp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileUpload',
        ),
    ]
