# Generated by Django 4.2.11 on 2024-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0014_rename_profile_profileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('pfp', models.ImageField(upload_to='profilepics')),
                ('description', models.CharField(max_length=240)),
                ('favourite', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileUpload',
        ),
    ]
