# Generated by Django 4.2.11 on 2024-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamelands', '0015_profile_delete_profileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics'),
        ),
    ]
